wandb_version: 1

s0:
  desc: null
  value: 20
n:
  desc: null
  value: 100
run_count:
  desc: null
  value: 100
d:
  desc: null
  value: 20
graph_type:
  desc: null
  value: ER
sem_type:
  desc: null
  value: gauss
methods:
  desc: null
  value:
  - notears
  - notears-np
_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696436213.060346
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.7.9
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
